import type { DesignSystemSpec, DesignToken, Component, TokenCategory } from '../types';

export function compileToContextMd(spec: DesignSystemSpec): string {
  const sections = [
    generateHeader(spec),
    generateTokensSection(spec.tokens),
    generateComponentsSection(spec.components),
    generateGuidelinesSection(spec.guidelines),
    generateAntiPatternsSection(spec.tokens, spec.components),
  ].filter(Boolean);

  return sections.join('\n\n---\n\n');
}

function generateHeader(spec: DesignSystemSpec): string {
  const sourceLines = Object.entries(spec.sources)
    .filter(([, v]) => v)
    .map(([k, v]) => `  - ${k}: ${v}`)
    .join('\n');

  return `# Design System Context

<!-- Generated by HANGOVER Spec Compiler v0.1.0 -->
<!-- Generated: ${spec.generatedAt} -->
<!-- Do not edit manually — run \`npm run compile\` to regenerate -->

## Sources
${sourceLines}

## Critical Rules

1. **Always use CSS custom properties** — never raw values like \`#2563EB\` or \`12px\`
2. **Use registered components** — never re-implement Button, Input, Card etc. as raw HTML
3. **Use semantic HTML** — never use \`<div onClick>\` instead of \`<button>\`
4. **Every form control needs a label** — bare \`<input>\` without label is an accessibility violation`;
}

function generateTokensSection(tokens: DesignToken[]): string {
  const categoryOrder: TokenCategory[] = ['color', 'spacing', 'typography', 'radius', 'shadow', 'z-index', 'other'];
  const grouped = groupByCategory(tokens);

  const tables = categoryOrder
    .filter(cat => grouped[cat]?.length)
    .map(cat => generateTokenTable(cat, grouped[cat]!));

  return `## Design Tokens

**Rule: Use \`var(--token-name)\`. Never use raw values.**

${tables.join('\n\n')}`;
}

function generateTokenTable(category: TokenCategory, tokens: DesignToken[]): string {
  const titles: Record<TokenCategory, string> = {
    color: 'Colors',
    spacing: 'Spacing (8pt grid)',
    typography: 'Typography',
    radius: 'Border Radius',
    shadow: 'Shadows',
    'z-index': 'Z-Index',
    other: 'Other',
  };

  const rows = tokens.map(t => `| \`${t.name}\` | \`${t.value}\` |`).join('\n');

  return `### ${titles[category]} (${tokens.length} tokens)
| Token | Value |
|-------|-------|
${rows}`;
}

function groupByCategory(tokens: DesignToken[]): Partial<Record<TokenCategory, DesignToken[]>> {
  const result: Partial<Record<TokenCategory, DesignToken[]>> = {};
  for (const token of tokens) {
    if (!result[token.category]) result[token.category] = [];
    result[token.category]!.push(token);
  }
  return result;
}

function generateComponentsSection(components: Component[]): string {
  if (components.length === 0) return '';

  const docs = components.map(generateComponentDoc).join('\n\n');

  return `## Component Catalog

**Rule: Use these registered components. Do not re-implement as raw HTML/CSS.**

${docs}`;
}

function generateComponentDoc(component: Component): string {
  const propsRows = Object.entries(component.props)
    .map(([name, prop]) => {
      const typeStr = prop.values
        ? prop.values.map(v => `\`"${v}"\``).join(' \\| ')
        : `\`${prop.type}\``;
      const required = prop.required
        ? '**Required**'
        : `Optional (default: \`${JSON.stringify(prop.default)}\`)`;
      return `| \`${name}\` | ${typeStr} | ${required} |`;
    })
    .join('\n');

  const examplesStr = component.examples
    .map(e => `\`\`\`tsx\n${e}\n\`\`\``)
    .join('\n');

  return `### ${component.name}

**Import:** \`import { ${component.name} } from '${component.import}'\`

${component.description}

**Props:**
| Prop | Type | |
|------|------|--|
${propsRows}

**Examples:**
${examplesStr}`;
}

function generateGuidelinesSection(guidelines: string): string {
  if (!guidelines.trim()) return '';
  return `## Usage Guidelines\n\n${guidelines}`;
}

function generateAntiPatternsSection(tokens: DesignToken[], components: Component[]): string {
  // Build NG→OK table from token categories
  const examplesByCategory: Partial<Record<TokenCategory, { ng: string; ok: string }>> = {
    color: { ng: `color: ${tokens.find(t => t.category === 'color')?.value ?? '#2563EB'}`, ok: `color: var(${tokens.find(t => t.category === 'color')?.name ?? '--color-primary'})` },
    spacing: { ng: `padding: ${tokens.find(t => t.category === 'spacing')?.value ?? '16px'}`, ok: `padding: var(${tokens.find(t => t.category === 'spacing')?.name ?? '--space-300'})` },
    typography: { ng: `font-family: Inter`, ok: `font-family: var(${tokens.find(t => t.category === 'typography' && t.name.includes('family'))?.name ?? '--font-family-base'})` },
    radius: { ng: `border-radius: ${tokens.find(t => t.category === 'radius')?.value ?? '8px'}`, ok: `border-radius: var(${tokens.find(t => t.category === 'radius')?.name ?? '--radius-md'})` },
  };

  const tokenRows = Object.values(examplesByCategory)
    .filter(Boolean)
    .map(({ ng, ok }) => `| \`${ng}\` | \`${ok}\` |`)
    .join('\n');

  const componentAntiPatterns = components
    .flatMap(c => c.antiPatterns)
    .map(ap => `\`\`\`tsx\n// NG\n${ap}\n\`\`\``)
    .join('\n');

  return `## Prohibited Patterns

### CSS Token Violations

| NG (raw value) | OK (token) |
|----------------|-----------|
${tokenRows}

### Component Anti-Patterns

${componentAntiPatterns}`;
}
